/// Flutter icons SkripsiIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SkripsiIcon
///      fonts:
///       - asset: fonts/SkripsiIcon.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SkripsiIcon {
  SkripsiIcon._();

  static const _kFontFam = 'SkripsiIcon';
  static const String? _kFontPkg = null;

  static const IconData wallet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_squared = IconData(0xf14b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chalkboard_teacher = IconData(0xf51c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_reader = IconData(0xf5da, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData business_time = IconData(0xf64a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
